#!/bin/bash

input_file="$1"
if [ ! -f "$input_file" ]; then
    echo "Error: Input file '$input_file' not found."
    exit 1
fi

filename=$(basename -- "$input_file")
filename_no_ext="${filename%.*}"
echo "The job is: ${filename_no_ext}"

export GAUSS_SCRDIR=~/scr
mkdir -p "$GAUSS_SCRDIR"

# Submit the job to SLURM
sbatch << EOF
#!/bin/bash
#SBATCH -J ${filename_no_ext}
#SBATCH -N 1
#SBATCH -n 40
#SBATCH -p normal
#SBATCH -o ${filename_no_ext}.log

cd $(pwd)
module load gaussian/g16C01

g16 $input_file
EOF

# chmod +x rg16, use rg16 in any directory(e.g., rg16 test.gjf)