#!/bin/bash

input_file="$1"
if [ ! -f "$input_file" ]; then
    echo "Error: Input file '$input_file' not found."
    exit 1
fi

filename=$(basename -- "$input_file")
filename_no_ext="${filename%.*}"
echo "The job is: ${filename_no_ext}"

# Submit the job to SLURM
sbatch << EOF
#!/bin/bash
#SBATCH -J ${filename_no_ext}
#SBATCH -N 1
#SBATCH -n 20
#SBATCH -p normal
#SBATCH -o ${filename_no_ext}.out

cd $(pwd)

module load orca/6.1.0
module load openmpi/4.1.8

/public/apps/orca-6.1.0/orca $input_file > ${filename_no_ext}.out
EOF

# chmod +x rorca, use rorca in any directory(e.g., rorca test.inp)