#!/bin/bash
function files_cleaner(){
echo "To clean the files with following keywords or regular expressions:"
for i in $keywords;do
  echo -n "[$i] "
done
echo "in the following pathway:"
echo "   V   V   V   V"
echo "$initial_path"
echo
echo "Press any key to start the cleaning process... ^v^"
read -n 1
for i in $keywords;do
  if [[ $flag_regex == 0 ]];then
    let file_counter+=$(find $initial_path -type f -name "$i" | wc -l)
    find $initial_path -type f -name "$i" | xargs rm -vf
  elif [[ $flag_regex == 1 ]];then
    i=".*"$i
    let file_counter+=$(find $initial_path -regextype "posix-egrep" -regex "$i" | wc -l)
    find $initial_path -regextype "posix-egrep" -regex "$i" | xargs rm -vf   
  fi
done
echo
echo -n "######  Total $file_counter files matching "
for i in $keywords;do
  echo -n "[$i] "
done
echo -n "keywords or regular expressions have been deleted  ######"
echo
} 



###################    files cleaner script begins from the following lines    ################### 
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
echo "*                 files cleaner script made by Jianyong Yuan              *"
echo "*                         E-mail: 404283110@qq.com                        *"
echo "*                Version 0.2 (dev), Release date: 2020-May-16             *"
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
echo
echo "                ************ Main Function Menu ************                "
echo "0 Customize keywords or regular expressions with which the files to be cleaned"
echo "1 Delete all checkpoint files [*.chk/*.fchk/*.fch] generated by Gaussian"
echo "2 Delete [*.gbw/*.loc/*.prop/*_property.txt] files generated by ORCA"
array_mainchoice=(0 1 2)
read mainchoice
while ! echo "${array_mainchoice[@]}" | grep -wq "$mainchoice" 
do
  echo "Please reinput function number..."
  read mainchoice
done
initial_path=$(pwd)
file_counter=0
if [[ $mainchoice == 0 ]];then
  array_customchoice=("yes" "no" "Y" "N" "y" "n")
  echo "Whether to use the regular expressions or not? [y/n]"
  read customchoice
  while ! echo "${array_customchoice[@]}" | grep -wq "$customchoice" 
  do
    echo "Please reinput your choice [y/n]..."
    read customchoice
  done
  if [[ $customchoice == "yes" || $customchoice == "y" || $customchoice == "Y" ]];then
    flag_regex=1
    echo "Please input the regular expressions splitted by the blank spaces"
  else
    flag_regex=0
    echo "Please input the keywords (wildcard "*" is also supported) splitted by the blank spaces"
  fi
  read keywords
  files_cleaner
elif [[ $mainchoice == 1 ]];then
  keywords="*.chk *.fchk *.fch"
  files_cleaner
elif [[ $mainchoice == 2 ]];then
  keywords="*.gbw *.loc *.prop *_property.txt"
  files_cleaner
fi

