#!/bin/bash
#PBS -l nodes=1:ppn=10
#PBS -q huge
#PBS -o TESTING 
#PBS -N g16.pbs
#PBS -j oe
#PBS -V 

g16root="/public/home/shixueliang/soft"
mkdir -p /public/home/shixueliang/soft/g16/scratch/"$PBS_JOBID"
GAUSS_SCRDIR="/public/home/shixueliang/soft/g16/scratch/$PBS_JOBID"
export g16root GAUSS_SCRDIR
. $g16root/g16/bsd/g16.profile

cp -rf $PBS_O_WORKDIR/$x $GAUSS_SCRDIR
cd $GAUSS_SCRDIR
g16 $x 
formchk *.chk
#mv *.log *.fchk $PBS_O_WORKDIR
mv *.log *.chk *.fchk *.rwf *.wfn *.cub $PBS_O_WORKDIR
rm -rf $GAUSS_SCRDIR


