#!/bin/csh

set WORK_DIR = ${PWD}
# job description in amber9: filename before last period
set JOB_NAME=$1:r
set JOB_OUT=${JOB_NAME}.out
# job name=dir tree + datetime +job description
set QSUB_SCRIPT = ${JOB_NAME}.sh
set outfile = ${JOB_NAME}.info
set errfile = ${JOB_NAME}.err

# BUILD THE QSUB_SCRIPT FILE
cat << EOF > ${WORK_DIR}/${QSUB_SCRIPT}
#!/bin/bash
#PBS -l nodes=comput120:ppn=12
#PBS -q small
#PBS -N $JOB_NAME
#PBS -j oe

#Please give the name of the INPUT_FILE, such as test(.chm)
INPUT_FILE=$JOB_NAME

#### orca ####

# ORCA-5.0.3
export PATH=/public/home/xlshi/soft/ORCA-5.0.3:\$PATH
export LD_LIBRARY_PATH=/public/home/xlshi/soft/ORCA-5.0.3:\$LD_LIBRARY_PATH
export ORCA=/public/home/xlshi/soft/ORCA-5.0.3/orca
alias orca='/public/home/xlshi/soft/ORCA-5.0.3/orca'

# openmpi411
export PATH=/public/home/xlshi/soft/openmpi-4.1.1/bin:\$PATH
export LD_LIBRARY_PATH=/public/home/xlshi/soft/openmpi-4.1.1/lib:\$LD_LIBRARY_PATH

export RSH_COMMAND="/usr/bin/ssh -x"

ulimit -s unlimited

#### dir ####
if [ ! -d /public/home/\$USER ]; then
  mkdir -p /public/home/\$USER
fi
if [ ! -d /public/home/\$USER/scr ]; then
  mkdir -p /public/home/\$USER/scr
fi
tmpdir=\$(mktemp -d /public/home/\$USER/${JOB_NAME}_XXXXXX)
cd \$tmpdir
echo tmpdir=\$tmpdir
cp \$PBS_O_WORKDIR/${JOB_NAME}.* .

echo "Job started from \${PBS_O_HOST}, running on 'hostname'" >> $outfile
echo "Job execution start: 'date'" >> $outfile
echo "PBS Job ID is: \${PBS_JOBID}" >> $outfile
cat \$PBS_NODEFILE >> $outfile
/public/home/xlshi/soft/ORCA-5.0.3/orca $1 > $JOB_OUT
cp \$tmpdir/* \$PBS_O_WORKDIR/

rm -rf \$tmpdir
EOF

#
#Now submit it to the PBS queue batch
#bad interpreter: No such file or directory
#win - unix
#dos2unix suborca
#
######

qsub -m n ${WORK_DIR}/${QSUB_SCRIPT}

######

################################################################################
#   Author: Hao Kang  email: hkangphy@gmail.com                                #
#   chmod +x suborcan 然后加到PATH里，suborcan test.inp                         #
################################################################################