#!/bin/bash
#PBS -N molclus_xtb
#PBS -l nodes=1:ppn=32
#PBS -l walltime=1440:00:00
#PBS -q CPU
#PBS -o jobID.$PBS_JOBID

function conformation_gen(){
cd gentor
echo -e "\n" | ./gentor                     			 
cp traj.xyz ../
cd ..
}
function configuration_gen(){
cd genmer
echo -e "\n" | ./genmer
cp traj.xyz ../
cd ..
}

export OMP_NUM_THREADS=32     # CPU cores for xtb
export OMP_STACKSIZE=3g       # memory for xtb
ulimit -s unlimited

cd $PBS_O_WORKDIR
touch jobID.$PBS_JOBID
chmod +x ./molclus            # add executable permission
chmod +x ./isostat
chmod +x ./gentor/gentor
chmod +x ./genmer/genmer

#conformation_gen                      # generate initial geometries (traj.xyz) by gentor
#configuration_gen                      # generate initial configurations (traj.xyz) by genmer

# The "ngeom=0" in the settings_xtb.ini file should be set!
# Start molclus with xtb
./molclus ./ini/settings_xtb.ini ./results/traj.xyz | tee ./results/molclus_info_xtb.txt

# Classify the optimized geometries into the clusters
./isostat isomers.xyz -Edis 0.5 -Gdis 0.4 -T 298 -nt 32 > ./results/isostat_info_xtb.txt

# Usage notes for the isostat tool:
# 比如执行isostat Rize.xyz -Nout 8 -Eout 2.4 -Edis 0.5 -Gdis 0.2 -T 350 -nt 32命令，代表将Rize.xyz 作为输入文件，往cluster.xyz里导出的簇是能量最低的8个且相对能量还必须在2.4 kcal/mol以内。使用0.5 kcal/mol和0.2埃分别作为归簇的能量和几何偏差判据。计算Boltzmann分布使用350K。使用32个线程并行计算。凡是通过命令行指定的参数就不需要在交互式界面里再输入。忘记这些选项怎么写的话可以随时运行isostat -h查看。

# Move the cluster.xyz and isomers.xyz files to the ./results/* directory
mv cluster.xyz ./results/cluster_xtb.xyz
mv isomers.xyz ./results/isomers_xtb.xyz







