#!/bin/bash
#PBS -N xtb-MD
#PBS -l nodes=1:ppn=32
#PBS -l walltime=1440:00:00
#PBS -q CPU
#PBS -o jobID.$PBS_JOBID

export OMP_NUM_THREADS=32     # CPU cores
export OMP_STACKSIZE=3g       # memory
ulimit -s unlimited

# mkdir -p ~/tmp/$PBS_JOBID
# scp -r master:$PBS_O_WORKDIR/* ~/tmp/$PBS_JOBID
# cd ~/tmp/$PBS_JOBID

cd $PBS_O_WORKDIR
touch jobID.$PBS_JOBID

FILENAME=test.xyz             # input file name
ini_temp=900                  # initial temperature (K)
interval_temp=50              # interval for temperature scanning (K)
nsteps_temp=1                 # nsteps for temperature scanning
total_time=100                # total simulation time (ps)
dump_time=50                  # interval for trajectory printout (fs)

cat << EOF > md.in  
\$md
   temp=300        # in K, thermostat temperature
   time=100        # in ps, total run time of simulation
   dump=50         # in fs, interval for trajectory printout
   step=1.0        # in fs, time step for propagation
   velo=false      # also write out velocities
   nvt=true        # perform simulation in NVT ensemble
   hmass=1         # do not change mass of hydrogens (default:4 times)
   shake=1         # use SHAKE algorithm to constrain bonds 0 = off, 1 = X-H only, 2 = all bonds
   sccacc=2.0      # accuracy of xTB calculation in dynamics
   restart=false   # read velocities from "mdrestart"
\$end
EOF

for ((i=0;i<=$nsteps_temp;i++));do
  temp=$(($ini_temp+$interval_temp*$i))
  sed -i "s/temp=.*        #/temp=$temp        #/" md.in     #  Modify the md.in file 
  sed -i "s/time=.*        #/time=$total_time        #/" md.in  
  sed -i "s/dump=.*        #/dump=$dump_time        #/" md.in 
  
  xtb $FILENAME --input md.in --omd --chrg 2 --uhf 0 --gfn 1 > ${FILENAME/%xyz/log} # running xtb-6.5.0
  
  mkdir scoords_${temp}K
  cp md.in scoords_${temp}K/
  mv scoord.* mdrestart xtbrestart scoords_${temp}K/
  mv ${FILENAME/%xyz/log} scoords_${temp}K/${FILENAME/%xyz/log}
  mv xtb.trj trj_${FILENAME%.xyz}_${temp}K_${total_time}ps.xyz
  rm wbo charges xtbopt.*
done

rm md.in


# scp -r ~/tmp/$PBS_JOBID/* master:$PBS_O_WORKDIR
# rm -rf ~/tmp/$PBS_JOBID

# task types: --sp --grad --opt [level] --hess --ohess [level] --md --omd
# solvent: --gbsa [solvent]  --alpb [solvent]
# charge: --chrg [value]
# unpaired electrons: --uhf [value]
# conversion: --molden 
# GFN2-xTB (default) / GFN1-xTB / GFN0-xTB : --gfn [value]
# convergence thresholds:  OPT:  --cycles [value]    SCC:  --iterations [value]
# Fermi-smearing: --etemp <REAL>
# difficulties of SCC convergence: xtb --etemp 1000.0 coord && xtb --restart coord



